exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
    args: [
      "--maxkb=1000",
    ]
  - id: check-ast
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: check-executables-have-shebangs
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']

# See: https://docs.astral.sh/ruff/integrations/#pre-commit
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.9
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.10
  hooks:
  - id: bandit
    args: [
      "-c",
      "pyproject.toml",
      "-q"
    ]
    additional_dependencies: [
      "bandit[toml]",
    ]
    exclude: "wd"


# Some other hooks you might want to consider:

# - repo: https://github.com/PyCQA/isort
#   rev: 5.13.2
#   hooks:
#   - id: isort

# - repo: https://github.com/psf/black
#   rev: stable
#   hooks:
#   - id: black
#     language_version: python3


# - repo: https://github.com/PyCQA/flake8
#   rev: 7.1.1
#   hooks:
#   - id: flake8
#   ## You can add flake8 plugins via `additional_dependencies`:
#   #  additional_dependencies: [flake8-bugbear]

## If you want to automatically "modernize" your Python code:
# - repo: https://github.com/asottile/pyupgrade
#   rev: v3.17.0
#   hooks:
#   - id: pyupgrade
#     args: ['--py38-plus']

## If you want to avoid flake8 errors due to unused vars or imports:
# - repo: https://github.com/PyCQA/autoflake
#   rev: v2.3.1
#   hooks:
#   - id: autoflake
#     args: [
#       --in-place,
#       --remove-all-unused-imports,
#       --remove-unused-variables,
#     ]

## If like to embrace black styles even in the docs:
# - repo: https://github.com/asottile/blacken-docs
#   rev: 1.18.0
#   hooks:
#   - id: blacken-docs
#     additional_dependencies: [black]

## Check for misspells in documentation files:
# - repo: https://github.com/codespell-project/codespell
#   rev: v2.3.0
#   hooks:
#   - id: codespell
